name: healthz-api-check

on: [pull_request]

jobs:
  pull-status-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: enviornment-setup
        run: |
          echo "Enviornment Setup"
          sudo apt install python3 python3-pip tree -y
          pip install --upgrade pip
          sudo apt install mysql-server
          pip install -r requirements.txt
      - name: healthz-check
          run: |
            python3 assignment2.py
            curl -vvvv http://localhost:8080/healthz

