name: healthz-api-check

on: [pull_request]

jobs:
  pull-status-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: enviornment-setup
        run: |
          echo "Enviornment Setup"
          sudo apt install python3 python3-pip tree -y
          pip install --upgrade pip
          pip install -r requirements.txt
#          sudo systemctl start mysql
          systemctl status mysql
      - name: healthz-check
        run: |
          python3 assignment2.py &
          sleep 3
          CODE=`curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:8080/healthz`
          echo $CODE
          if [ $CODE != "200" ]
          then
            echo "Exiting"
            exit 1
          else
            echo "SUCCESS"
            kill -9 `lsof -i:8080 -t`
          fi