name: healthz-api-check

on: [pull_request]

jobs:
  pull-status-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: enviornment-setup
        run: |
          echo "Enviornment Setup"
          sudo apt install python3 python3-pip tree -y
          pip install --upgrade pip
          pip install -r requirements.txt
          sudo systemctl start mysql
          systemctl status mysql
      - name: healthz-check
        run: |
          python3 assignment2.py &
          sleep 3
      - name: Failure
        if: curl  -w "%{http_code}" http://localhost:8080/healthz == '503'
        run: exit 1
      - name: Sucsess
        if: curl  -w "%{http_code}" http://localhost:8080/healthz == '200'
        run: |
          echo "Sucsess"
          sleep 5
          kill -9 `lsof -i:8080 -t`